### ISSUE TITLE
Code block font size is huge on iOS Safari

### ISSUE THREAD

**Issue by cassidyjames** [elementary/blog-template#2]
From https://github.com/elementary/blog/issues/49 by @danrabbit 

>Oops
>
>![8299DD54-9B30-4E61-9096-709D22D8AC91](https://user-images.githubusercontent.com/7277719/63139518-65c4ba00-bf93-11e9-8305-6edad97e0383.png)

**Comment by cassidyjames** [comment]
@danrabbit hrm wtf, this shouldn't be that big :sweat_smile: Can't reproduce in Firefox or Chrome on elementary OS, or Firefox/Firefox Focus on Android:

![Screenshot_20190815-205423](https://user-images.githubusercontent.com/611168/63140372-f3f26d80-bf9e-11e9-86ce-e289824c5f7b.png)

Must be iOS-specific?

**Comment by cassidyjames** [comment]
Also showing up correctly in Chrome on Android

![Screenshot](https://i.imgur.com/t2FoUcp.png)

**Comment by cassidyjames** [comment]
@micahilbery:

>Through some searching it looks like iOS might ignore some of the sites font sizes and resize to whatever it deems necessary. You could try adding `-webkit-text-size-adjust: none;` to the `<pre>` tag and see if that fixes. Sorry I don't have access to iOS to test.

**Comment by michallepicki** [comment]
I could reproduce on iPhone 8 on Browserstack, seems to be happening only when code block is inside figure: https://michallepicki.github.io/test/

I'd like to have these two code blocks to look the same anyway, so I can look into fixing this later today / tomorrow.
