### ISSUE TITLE
Better inline code styles

### ISSUE THREAD

**Issue by cassidyjames** [elementary/blog-template#4]
From https://github.com/elementary/blog/issues/3

>Right now they're just mono, but we usually set a gray background color, too.

**Comment by michallepicki** [comment]
They do have a very light gray background right now:
![image](https://user-images.githubusercontent.com/4972756/66252420-bff42700-e75b-11e9-8ecd-86988f367148.png)
Do we want to make the gray background a bit darker?

**Comment by cassidyjames** [comment]
Ah, that'd be up to @danrabbit. This should have actually been closed by #16.
