### ISSUE TITLE
Show more from this tag at the bottom of each post

### ISSUE THREAD

**Issue by danrabbit** [elementary/blog-template#41]
## Problem

At the moment we're still getting a ton of clicks on that Medium link and I wonder if it's because of how prominently that looks like where you go to read more stories after the one or two suggested "Up Next" posts

## Proposal

Show 3 (or maybe even 6) stories below "Up Next" (using the smaller card size from the homepage) from the same tags as the published story. So for example if you're reading a design post, we show more design posts you could read. This could be a good way to surface older posts and drive engagement towards similar content

## Prior Art

On Medium, directly below the post they show "related reads", but from other publishers.

**Comment by cassidyjames** [comment]
Fixed in 411257af5233f55da7acd1cd6691c15c3b86977b
