### ISSUE TITLE
Secondary nav wrap issues on tiny screens

### ISSUE THREAD

**Issue by cassidyjames** [elementary/blog-template#8]
From https://github.com/elementary/blog/issues/34

>Like iPhone 5/SE (tested in Firefox Responsive mode with the iPhone SE preset):
>
>![image](https://user-images.githubusercontent.com/611168/62797522-267d0180-ba99-11e9-98ed-10a7a21f1596.png)

**Comment by dar5hak** [comment]
I tried adding a `white-space: nowrap;` to the `<a>` tags. It added a horizontal scroll bar just like the primary nav.

![Screenshot from 2019-09-25 22-52-20](https://user-images.githubusercontent.com/8205055/65624334-420b7f80-dfe7-11e9-9384-a7651873a438.png)

That looks a bit awkward to me, but letting the flexbox wrap with `flex-wrap: wrap;` gives this:

![Screenshot from 2019-09-25 22-56-29](https://user-images.githubusercontent.com/8205055/65624539-be9e5e00-dfe7-11e9-8b89-6908871a0a91.png) 

What do you think?

**Comment by cassidyjames** [comment]
@dar5hak naively I'm fine with the first (it's similar to the main site), but I would be good with the wrapped version if we decreased the vertical spacing a little bit.

**Comment by dar5hak** [comment]
@cassidyjames How does this look?

![Screenshot from 2019-09-25 23-31-50](https://user-images.githubusercontent.com/8205055/65627310-bdbbfb00-dfec-11e9-912e-3551bab77656.png)

I reduced the `line-height` to `3rem` and added a small vertical to the flexbox.

(TBH even I'm leaning towards the scroll bar approach now. This looks kinda confusing.)

**Comment by cassidyjames** [comment]
@dar5hak yeah I think I'm leaning toward the horizontal scrolling as well :)

**Comment by dar5hak** [comment]
Considering that scroll bars don't show up by default on Android (and I'm almost sure iOS), it makes sense to go with those.

I'll make a PR once I get home.
